### ISSUE TITLE
Prepending whitespace on input

### ISSUE THREAD

**Issue by jeroneemou** [jenstornell/tiny-html-minifier#15]
Heyo, 

when you run with input example of ` <header class="mod-header"> </header>` with additional whitespace before it will prepend additional `<` due to it like `<<header class="mod-header"> </header>`

I recommend trim `$html` first.

```
function parser($html) {
        $split = explode('<', trim($html));
```

**Comment by jenstornell** [comment]
I've made a complete rewrite and I don't think this is an issue anymore. At least, I can't reproduce it.
