### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by jeroneemou** [jenstornell/tiny-html-minifier#16]
Hey man, 

good work with minifier, small tip for you :)

There is simplicity you could introduce to some statements.
Look at `return (in_array($name, $this->elements)) ? true : false;`. You could make it way more readable and shorter by just returning `return in_array($name, $this->elements);`

Take care 👍

**Comment by jenstornell** [comment]
I agree. That is smarter. Anyway, I've made a rewrite to support Custom Elements and that code is not existing anymore.

Thanks anyway!
