### ISSUE TITLE
removeComments breaks html sometimes

### ISSUE THREAD

**Issue by NeoMarine** [jenstornell/tiny-html-minifier#26]
In some cases I've found removeComments to kill the html for me- I believe it's mostly because sometimes servers deliver conditional rendering depending on some comment tags. Ideally I would recommend having an option to disable the "removeComments()" - otherwise all is good - I am using a modified version of your script (that just removes the aforementioned function).

**Comment by MuetzeOfficial** [comment]
Six months later, I have the same problem. It will probably not be fixed...

**Comment by jenstornell** [comment]
@NeoMarine @MuetzeOfficial 

I'm aware that I'm not the fastest to respond. I've now implemented the code you suggested. It works well in my tests and I hope it does not break anywhere. Thanks!
