### ISSUE TITLE
Leading Document Whitespace adds superfluous <

### ISSUE THREAD

**Issue by alpipego** [jenstornell/tiny-html-minifier#27]
When a document has whitespace before the doctype declaration, it adds a superfluous `<` before the document. I've worked around this by trimming the `$element` and ignoring empty elements in:

https://github.com/jenstornell/tiny-html-minifier/blob/master/tiny-html-minifier.php#L151-L164

```
// Strip whitespace from element
    function stripWhitespace($element) {
        if($this->skip == 0) {
            $element = preg_replace('/\s+/', ' ', $element);
        }
        return trim($element);
    }

    // Add chevrons around element
    function addChevrons($element, $noll) {
        if (empty($element)) {
            return $element;
        }
        $char = ($this->contains('>', $noll)) ? '>' : '';
        $element = '<' . $element . $char;
        return $element;
    }
```
But I don't know if this is a good solution for all cases. Seems somewhat related to #15.

**Comment by jenstornell** [comment]
I've implemented your fix. Thank you so much for the time you saved me.
