### ISSUE TITLE
Missing svg elements

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/tiny-html-minifier#5]
https://developer.mozilla.org/en-US/docs/Web/SVG/Element

**Comment by inoas** [comment]
... missing in what way?

**Comment by jenstornell** [comment]
It does not minify svg elements.

**Comment by inoas** [comment]
Because you are doing opt-in instead of opt-out, aka parse a fixed element list?

**Comment by jenstornell** [comment]
Yes, I have like a whitelist of elements that should be minified. Svg elements are not yet included.

**Comment by jenstornell** [comment]
@inoas SVG files as well as Custom Elements are now minified. I no longer keep a "whitelist" of elements. Much smarter now I think and I even saved a 100 rows as bonus.
