### ISSUE TITLE
Why is //<![CDATA[ being stripped?

### ISSUE THREAD

**Issue by inoas** [jenstornell/tiny-html-minifier#9]
It should not. Is it because it is a comment?

**Comment by jenstornell** [comment]
I think you are right. I will look into it.

**Comment by jenstornell** [comment]
A bit late maybe but I've fixed it now.

https://github.com/jenstornell/tiny-html-minifier/commit/312d757b221ee0a77e2a07f7ac837a1fcbc2415f#diff-9edd37544d797d61adcfba07c310feb2L23

**Comment by inoas** [comment]
Thank you. Next time I get around I will report back :)
